### ISSUE TITLE
top99 에 랭킹 변화 추이 내용 추가

### ISSUE THREAD

**Issue by orgpark** [orgpark/fym_mobile#111]
http://www.feedyourmusic.com/api/v1/top99 에 ranking_difference라는 항목 추가
new 일 경우 null value로 입력

**Comment by orgpark** [comment]
@kyo504 ranking_difference라는 항목 추가되었으니 이를 이용해서 차트의 경우에는 랭킹변동 추이 표시 Please

**Comment by kyo504** [comment]
완료(#113)
