### ISSUE TITLE
네이티브모듈 이용해서 플레이어 적용 (iOS)

### ISSUE THREAD

**Issue by good2hear** [orgpark/fym_mobile#12]

**Comment by good2hear** [comment]
- 완료
- [react-native-player ](https://github.com/kyo504/react-native-player) 에 적용 필요

**Comment by orgpark** [comment]
iOS에서 간단한 샘플페이지 만들어서 필요한 정보를 앱에서 표시해줄 수 있는지 체크하고 wrapping 작업으로 들어가면 좋을 듯 함

**Comment by good2hear** [comment]
-  완료 : status (play/pause), duration, current time 등 앱에서 표시
