### ISSUE TITLE
네이티브모듈 이용해서 플레이어 적용 (android)

### ISSUE THREAD

**Issue by good2hear** [orgpark/fym_mobile#13]
- Android 에서 제공하는 Streaming 관련한 Audio API를 검토
- 모듈화해서 Native Module로 React Native와 연동

**Comment by kyo504** [comment]
- [react-native-player](https://github.com/kyo504/react-native-player)를 fork해서 관리
- Android에서 기본적인 동작이 잘 되는 것 [샘플앱](https://github.com/kyo504/react-native-streaming)을 통해서 확인

**Comment by kyo504** [comment]
완료(#14)
