### ISSUE TITLE
새로 등록된 곡들에 대한 리스트 구현

### ISSUE THREAD

**Issue by kyo504** [orgpark/fym_mobile#21]
- 리스트 디자인에 대한 고민 필요
 - 일반적인 리스트 형태로 갈까?
 - SoundCloud 처럼 형태로 갈까?
 - GridListView 형태로 갈까?

**Comment by orgpark** [comment]
SoundCloud형태의 뉴스피드모양 좋을 듯

**Comment by kyo504** [comment]
완료(#37)
