### ISSUE TITLE
/api/v1/test

### ISSUE THREAD

**Issue by orgpark** [orgpark/fym_mobile#29]
로그인 후 resonse 받아오는 내용 확인

**Comment by good2hear** [comment]
![with token](https://cloud.githubusercontent.com/assets/8426267/17764387/ef92b828-6559-11e6-8d0e-5fa73b320116.png)

헤더에 'Authorization': accessToken 을 넣어서 보내보고, 헤더자체를 빼서 보내봤는데 둘다 response 가 같았습니다

**Comment by good2hear** [comment]
돈
