### ISSUE TITLE
Bug Report 기능 추가

### ISSUE THREAD

**Issue by orgpark** [orgpark/fym_mobile#45]
개선사항 요청할 수 있는 란 만들어서 유저의 컴플레인 받음

**Comment by kyo504** [comment]
### 요구사항
- floating action 버튼 추가
- 버튼 선택 시 페이지 전환
- 해당 페이지에서 사용자가 코멘트 입력 후 `submit`버튼을 인가하면 서버쪽에 전송
- 서버쪽 구현은 여기(#46) 참고

**Comment by kyo504** [comment]
완료(#61)
