### ISSUE TITLE
이어폰 콘트롤

### ISSUE THREAD

**Issue by orgpark** [orgpark/fym_mobile#59]
### Issue
- 음악 재생 중에 이어폰으로 컨트롤이 안됨
- 재생, 멈춤, 이전, 다음
- iOS에서는 동작 오류 확인, Android도 확인 필요

**Comment by kyo504** [comment]
@good2hear iOS에서 이거 안 되던데 이것도 확인 좀 해줘

**Comment by good2hear** [comment]
요고 background 에서 play 되는거 고치고나니까 xcode 로 돌렸을때는 play 되었구요. 
이따가 제대로 깔아서 다시 테스트 해보겠습니다.

**Comment by good2hear** [comment]
- iOS 완료

**Comment by kyo504** [comment]
Android는 리모컨 달린 이어폰이 없어서 현재 테스트 불가. 필요 시에 다른 이슈 발행하여 진행.
