### ISSUE TITLE
Artist 페이지 구현

### ISSUE THREAD

**Issue by kyo504** [orgpark/fym_mobile#69]
- 다른 앱 벤치마킹 필요
- 필요한 정보
 - 이름
 - 이메일
 - 프로필 사진
 - Follower 수
 - 곡 올린 개수 및 리스트
 - 올린 앨범 개수 및 리스트 
 - 올린 플레이리스트 개수 및 리스트

**Comment by kyo504** [comment]
@orgpark 위에 정보 참고해서 API 뚫어주면 될 것 같아

**Comment by orgpark** [comment]
아래와 같이 구현했음. (토큰 필요 없음...)
* get /api/v1/artist_info DONE

request parameters: {id (of artist. 곡들 나열된 json상에서는 student_id가 되겠음)}
return values: {:id, :email, :username, :avatar_url, :full_name, :rap_name, :my_likes, :followers, :favorite_artists, :followers}

**Comment by orgpark** [comment]
return values updated above

**Comment by kyo504** [comment]
완료(#102)
