### ISSUE TITLE
[iOS] 진동모드인 경우 디바이스에서 소리 안남

### ISSUE THREAD

**Issue by kyo504** [orgpark/fym_mobile#76]
### Issue
- iOS 디바이스에서 진동모드로 하면 소리가 안나고 풀면 소리가 남. 
- 진동모드에서 이어폰을 꽂으면 이어폰으로 소리가 난다

**Comment by kyo504** [comment]
@good2hear 규민아 시간나면 이거 확인 좀 해줘~

**Comment by good2hear** [comment]
완료
